package lotto.ui

enum class Error(val message: String) {
    BONUS("BONUS NUMBER MUST NOT BE IN THE WINNING LOTTO"),
    LOW_PURCHASE_AMOUNT("PURCHASE AMOUNT MUST ABOVE OR EQUAL TO 1000"),
    NOT_DIVISIBLE_BY_1000("PURCHASE AMOUNT MUST DIVISIBLE BY 1000"),
    INVALID_INPUT("INVALID INPUT"),
}
